steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_ARTIFACT_REGISTRY_IMAGE/$_SERVICE_NAME:$COMMIT_SHA'
      - '-f'
      - server/Dockerfile
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_ARTIFACT_REGISTRY_IMAGE/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_ARTIFACT_REGISTRY_IMAGE/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--allow-unauthenticated'
    id: Deploy
    entrypoint: gcloud
substitutions:
  _ARTIFACT_REGISTRY_IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy
  _SERVICE_NAME: roast-ritual
  _DEPLOY_REGION: us-central1
